name: hello world
on:
  push:
    branches:
      - main
jobs: 
  first-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/cjeckout@v3
      - name: print message
        run: echo "Hello world GA testing"
